### ISSUE TITLE
problem with saturday

### ISSUE THREAD

**Issue by mohammadkhoeini** [m-khosravi/angular2-persianDate-pipe#2]
Hi buddy,
Thanks for your effort in advance.
There is a bug with saturday in your service.
Try a date that should be converted to saturday it gives undefined.(like  2018-02-17T10:21:00)

**Comment by mohammadkhoeini** [comment]
you can fix this issue by this change:

>   toPersian(gregorianDate:Date) {
>     if ((this.gregorianYear % 4) != 0)
>       this.farsiDate = this.func1();
>     else
>       this.farsiDate = this.func2();
>     this.strMonth = this.monthNames[Math.floor(this.month - 1)];
>     //this.strWeekDay = this.weekDayNames[this.WeekDay + 1];
>     console.log("date1111111111111111111111111111111")
>     if (this.WeekDay == 6) {
>         this.strWeekDay = this.weekDayNames[0];
>     } else {
>         this.strWeekDay = this.weekDayNames[this.WeekDay + 1];
>     }
> 
>   }

**Comment by m-khosravi** [comment]
Hi 
I will fix this problem on next update 
Tanks for your report
